function eigenstring = eigToVm(eigenvector, basisfunctions, maxl)
% function eigenstring = eigToVm(eigenvector, basisfunctions, maxl)
%{
Takes an eigenvector generated by diagonalizing the coupling matrix
returned from SigmaSolve (either a bunch of singles or full), and generates
a string of weighted Sigma_m,l's to apply to the SigmaSolve function again.
Austin Reid 2020.07.19
%}


if ~exist('maxl','var') || isempty(maxl)
  maxl=10;
end

if ~exist('basisfunctions','var') || isempty(basisfunctions)
  basisfunctions = 'MagneticBasis.txt';
end


fid=fopen(basisfunctions);
tline = fgetl(fid);
basisl = cell(0,1);
while ischar(tline)
    basisl{end+1,1} = tline;
    tline = fgetl(fid);
end
fclose(fid);

source = cell(0,1);
for l = 1:maxl
    source{l,1} = split(basisl{l}(2:end-1),', ');
end

% Flatten basis*Vm cell array and l,m label cell array
sourcecell = vertcat(source{:});

eigenstring = '';
for i=1:length(eigenvector)
    vn = num2str(eigenvector(i),'%4.6e');
    sigman = sourcecell{i};
    if eigenvector(i)<0
        pm = '-';
        vn = vn(2:end);
    else
        pm = '+';
    end
    eigenstring = [eigenstring pm vn '*(' sigman ')'];
end
eigenstring = eigenstring(2:end);

end