function couplings = projectedSigma(nV, resolution, bubble, maxl)
% function couplings = projectedSigma(nV, resolution, bubble, maxl)
%{
Generates a new coupling matrix, where each element was stimulated by the
eigenvector generated by diagonalizing the fullSigmaSolve coupling matrix.
Austin Reid 2020.07.20
%}

if ~exist('maxl','var') || isempty(maxl)
  maxl=3;
end

couplings = zeros(maxl^2+maxl);
for l = 1:maxl
    for m = 0:(2*l)
        eigenstring = eigToVm(nV(:,l+m), [], maxl);
        couplings(l+m,:) = singleSigmaSolve(eigenstring, round(resolution/sqrt(l)),[],bubble,maxl);
        ModelUtil.remove('Model')
    end
end
end